#!/bin/bash

# reset
color_off='\o033[0m'       # text reset

# regular colors
black='\o033[0;30m'        # black
red='\o033[0;31m'          # red
green='\o033[0;32m'        # green
yellow='\o033[0;33m'       # yellow
blue='\o033[0;34m'         # blue
purple='\o033[0;35m'       # purple
cyan='\o033[0;36m'         # cyan
white='\o033[0;37m'        # white

# bold
bblack='\o033[1;30m'       # black
bred='\o033[1;31m'         # red
bgreen='\o033[1;32m'       # green
byellow='\o033[1;33m'      # yellow
bblue='\o033[1;34m'        # blue
bpurple='\o033[1;35m'      # purple
bcyan='\o033[1;36m'        # cyan
bwhite='\o033[1;37m'       # white

# underline
ublack='\o033[4;30m'       # black
ured='\o033[4;31m'         # red
ugreen='\o033[4;32m'       # green
uyellow='\o033[4;33m'      # yellow
ublue='\o033[4;34m'        # blue
upurple='\o033[4;35m'      # purple
ucyan='\o033[4;36m'        # cyan
uwhite='\o033[4;37m'       # white

# background
on_black='\o033[40m'       # black
on_red='\o033[41m'         # red
on_green='\o033[42m'       # green
on_yellow='\o033[43m'      # yellow
on_blue='\o033[44m'        # blue
on_purple='\o033[45m'      # purple
on_cyan='\o033[46m'        # cyan
on_white='\o033[47m'       # white

# high intensity
iblack='\o033[0;90m'       # black
ired='\o033[0;91m'         # red
igreen='\o033[0;92m'       # green
iyellow='\o033[0;93m'      # yellow
iblue='\o033[0;94m'        # blue
ipurple='\o033[0;95m'      # purple
icyan='\o033[0;96m'        # cyan
iwhite='\o033[0;97m'       # white

# bold high intensity
biblack='\o033[1;90m'      # black
bired='\o033[1;91m'        # red
bigreen='\o033[1;92m'      # green
biyellow='\o033[1;93m'     # yellow
biblue='\o033[1;94m'       # blue
bipurple='\o033[1;95m'     # purple
bicyan='\o033[1;96m'       # cyan
biwhite='\o033[1;97m'      # white

# high intensity backgrounds
on_iblack='\o033[0;100m'   # black
on_ired='\o033[0;101m'     # red
on_igreen='\o033[0;102m'   # green
on_iyellow='\o033[0;103m'  # yellow
on_iblue='\o033[0;104m'    # blue
on_ipurple='\o033[0;105m'  # purple
on_icyan='\o033[0;106m'    # cyan
on_iwhite='\o033[0;107m'   # white

IFS=

while read -r line
do
  if [[ "$line" =~ ^\|.* ]]; then
    echo $line \
      | sed -e 's,^|,{,g' -e 's,|$,},g' \
      | sed \
      -e "s,[o*],${green}&${color_off},g" \
      -e "s,[v:],${ired}&${color_off},g" \
      -e "s,[\\/|-],${blue}&${color_off},g" \
      -e "s,[+],${purple}&${color_off},g" \
      -e 's,^{,|,g' \
      -e 's,}$,|,g'
  else
    echo $line
  fi
done

