#!/bin/bash

IFS=

function horiz_flip() {
  while read -r line
  do
    if [[ "$line" =~ ^\|.* ]]; then
      echo $line | \
        sed -e 's,\\,{,g' \
            -e 's,/,\\,g' \
            -e 's,{,/,g' \
            -e 's,%,(,g' \
            -e 's,\&,%,g' \
            -e 's,(,\&,g' | \
        rev
    else
      echo $line
    fi
  done
}

function vert_flip() {
  tac | \
  sed -e 's,\\,{,g' -e 's,/,},g' | \
  sed -e 's,{,/,g' -e 's,},\\,g'
}

function usage() {
cat <<EOF
$0 [ -t | -v | -h ]
  -h - this message
  -t - flip board horizontally, right-to-left, like turing over the page
  -v - flip board upside down
EOF
}

if [[ "$#" -eq 0 ]]; then
  vert_flip
else
  while getopts "tvh" OPT
  do
    case $OPT in
      't') horiz_flip ;;
      'v') vert_flip ;;
      'h') usage; exit 0;;
    esac
  done
fi

