#!/bin/bash

set -f

g_mtx_row() {
  [[ -z "$1" ]] && return

  local c=0
  local line="| "
  local col=$1

  while [[ $c -lt $col ]]
  do
    line="${line}. "
    let c++
  done

  line="${line}|"
  echo "$line"
}

g_empty_row() {
  [[ -z "$1" ]] && return
  col=$1
  len=$(($col*2))
  printf '| %*s|\n' "$len"
}

overlay() {
  local src=$1
  local pat=$2
  local dst=""
  local i=0
  local route_symb="\|/\\-+\ "

  while [[ $i -lt ${#src} ]]
  do
    ch="${src:$i:1}"
   
    if [[ "${ch}" == '*' || "${route_symb/$ch}" == "$route_symb" ]]; then
      dst="${dst}${ch}"
    else
      dst="${dst}${pat:$i:1}"
    fi
    
    let i++
  done
    
  echo "${dst}"
}

cl_mtx_row=""
col_num=0
parity="1"

while read -r line
do
  [[ "$line" =~ ^\+.* ]] && echo $line && continue
  [[ $col_num -eq 0 ]] && col_num=$(((${#line}-3)/2))
  [[ -z "$cl_mtx_row" ]] && cl_mtx_row=$(g_mtx_row $col_num)
  
  if [[ "$parity" == "1" ]]; then
    k=$(echo "$line" | wiring)
    k=$(overlay "$k" "$cl_mtx_row")
    echo "$k" | sed 's/\./:/g'
    parity="2"
  else
    g_empty_row $col_num
    parity="1"
  fi
done
