#!/bin/bash

filter() {
  sed -e "s/#/ /g" \
      -e "s/\^/o/g" \
      -e "s/[VT><]/o/g" \
      -e "s/&/\\\/g" \
      -e "s/%/\//g" \
      -e "s/l/|/g" \
      -e "s/~/-/g"
}

filter

#while read -r line
#do
#  echo "$line" | filter
#done
